[project]
name = "codingtest"
version = "0.1.0"
description = "baeckjoon & programmers Coding Test"
authors = [
    {name = "wallace",email = "j76067469@gmail.com"}
]
readme = "README.md"
requires-python = "^3.10"
dependencies = [
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
